### ISSUE TITLE
Give meaning to Foobar Layer

### ISSUE THREAD

**Issue by Disastergirl** [Disastergirl/Kaleidoscope#7]
Options:

-Perlin Noise here could be replaced by environmental noise- "Rustle Noise", including random pulses characterised by the rustle time (the mean interval between pulses), with little or no pitch.

-Using the clock-face tonality scale, the movement of the triangle strip would transform

-Harmonics?

-more coming..

**Comment by davidfoerster** [comment]
This issue was moved to davidfoerster/KaleidOK-examples#13
