### ISSUE TITLE
Translate Transcription

### ISSUE THREAD

**Issue by Disastergirl** [Disastergirl/Kaleidoscope#8]
Use the Google Translate API to translate languages other than English (primarily Dutch and German) into English.

**Comment by davidfoerster** [comment]
Please describe, in which situation which text is supposed to be translated. How should the application determine, from which language to translate or whether there is translation necessary at all? Are there any dependencies or interactions with the other speech or text processing steps already performed?

**Comment by Disastergirl** [comment]
In which situation which text is supposed to be translated?
A user speaks in their language, this is then transcribed to text and then the text is translated into English. This translated English text is then used for the remaining processes.

How should the application determine, from which language to translate or whether there is translation necessary at all?
If automatic language detection is not possible (as is when using Google translate), then we would have to manually pre-determine which language would be used for the upcoming users. Ideally any languages other than English would be detected and translate to English. Unless we translate the whole lexicon..

Are there any dependencies or interactions with the other speech or text processing steps already performed?
Not sure.

**Comment by davidfoerster** [comment]
How simple does an explicit language switch need to be during operation? I'll try to suggest some possible user interface designs with different levels of required implementation effort as questions:
- Is an application restart for each language switch feasible?
- Is an obscure (but documented) key combination and an interaction feedback in the terminal output sufficient?
- If neither is the case, do you see yourself capable of designing and/or implementing a user interface element fit to the task?

**Comment by Disastergirl** [comment]
For this state an application restart is feasible. I just want to try it out.
Key combination would be great.
I'm not even thinking of a user interface for the task until it has been tried out.
--I'd like to do interface design for all optionable features at a later stage in the project.. next year most likely

**Comment by davidfoerster** [comment]
Thanks, that should be enough to get started.
